In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow.keras.layers import Dense, Input, Dropout, Attention
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.metrics import classification_report

In [4]:
data = pd.read_excel("/content/Main Data Set.xlsx")
x = data.iloc[:, :-2]
y = data.iloc[:, -1]
data



0           1          2          3          4          5  \
0    -371.82810  108.495650  11.329577  22.444440  22.374722   5.689639   
1    -399.31082  112.921510   6.919172  21.663918  18.155872   7.181758   
2    -367.67980  100.844460   0.920031  23.759985   9.670633   1.539028   
3    -355.13303  101.861480   0.237188  32.159462  22.914465   3.906355   
4    -425.16406  129.036560   0.186828  16.686668  23.938263  10.088806   
...         ...         ...        ...        ...        ...        ...   
2995 -330.74442  119.453470 -28.931398  16.431282 -25.923940 -22.580963   
2996 -313.88834   99.268030 -26.273092   4.311078 -19.713417 -18.493284   
2997 -324.29977  129.237520 -33.933000  11.158257 -17.881138 -26.475191   
2998 -352.44968  148.348430 -32.924522   6.316973  -8.765810 -28.446260   
2999 -354.54044   97.072136 -24.854030   9.664994 -23.980673 -14.894958   

              6          7          8         9  ...        31        32  \
0     -5.820382  -1.952239 -16.463146  6.061418  ... -2.383272 -1.047149   
1     -1.518631   0.581832 -18.784006  3.909678  ... -1.837900 -0.798910   
2     -6.678311  -0.632159 -19.383781  8.799910  ... -2.202147 -0.537667   
3     -5.871533  -1.297926 -20.633438  7.027359  ... -1.725350 -0.643298   
4     -2.028934  -2.977077 -19.282000  3.621475  ... -3.425826  0.476763   
...         ...        ...        ...       ...  ...       ...       ...   
2995 -18.477665 -22.479776   0.922552 -7.602468  ...  0.742409 -3.576027   
2996 -15.861244 -10.180239  -4.867939 -0.662536  ...  1.392444 -0.948494   
2997 -13.977830 -16.337875  -0.353709 -4.651527  ...  1.154832 -4.393998   
2998 -14.844326 -19.795837  -4.025840 -4.273027  ...  0.961699 -3.170674   
2999 -15.025388 -19.491266  -0.536067 -6.233265  ...  3.516302 -1.918456   

            33        34        35        36        37        38  gender  \
0    -5.113010 -3.650117 -3.092591 -1.955777 -4.405060 -4.580990    male   
1    -4.694558 -4.464447 -1.893085 -2.912510 -4.858458 -4.174491    male   
2    -3.844402 -2.821896 -2.086511 -2.610275 -4.089844 -5.701215    male   
3    -3.470233 -2.856177 -2.057140 -1.870503 -4.755356 -4.600479    male   
4    -4.416140 -2.720565 -2.072952 -1.341345 -5.566973 -4.696309    male   
...        ...       ...       ...       ...       ...       ...     ...   
2995 -1.591279 -3.515108 -3.029455 -3.592587 -2.900054  0.754864  female   
2996 -3.438912  0.659637 -0.903038 -1.892453 -2.112316 -1.224023  female   
2997 -5.090885 -2.760841 -1.561349 -3.028061 -4.226657  3.758476  female   
2998 -4.107362 -6.001142 -4.654924 -3.437292 -3.550606 -0.757205  female   
2999 -0.355499 -1.424978 -2.336957 -1.454762 -6.149889  0.243947  female   

      label  
0     adult  
1     adult  
2     adult  
3     adult  
4     adult  
...     ...  
2995  child  
2996  child  
2997  child  
2998  child  
2999  child  

[3000 rows x 41 columns]

In [5]:
y

0       adult
1       adult
2       adult
3       adult
4       adult
        ...  
2995    child
2996    child
2997    child
2998    child
2999    child
Name: label, Length: 3000, dtype: object

In [6]:
x

0           1          2          3          4          5   \
0    -371.82810  108.495650  11.329577  22.444440  22.374722   5.689639   
1    -399.31082  112.921510   6.919172  21.663918  18.155872   7.181758   
2    -367.67980  100.844460   0.920031  23.759985   9.670633   1.539028   
3    -355.13303  101.861480   0.237188  32.159462  22.914465   3.906355   
4    -425.16406  129.036560   0.186828  16.686668  23.938263  10.088806   
...         ...         ...        ...        ...        ...        ...   
2995 -330.74442  119.453470 -28.931398  16.431282 -25.923940 -22.580963   
2996 -313.88834   99.268030 -26.273092   4.311078 -19.713417 -18.493284   
2997 -324.29977  129.237520 -33.933000  11.158257 -17.881138 -26.475191   
2998 -352.44968  148.348430 -32.924522   6.316973  -8.765810 -28.446260   
2999 -354.54044   97.072136 -24.854030   9.664994 -23.980673 -14.894958   

             6          7          8         9   ...        29        30  \
0     -5.820382  -1.952239 -16.463146  6.061418  ... -0.184623 -2.057550   
1     -1.518631   0.581832 -18.784006  3.909678  ... -0.946463 -0.529916   
2     -6.678311  -0.632159 -19.383781  8.799910  ...  1.907667 -1.688837   
3     -5.871533  -1.297926 -20.633438  7.027359  ...  1.061948 -3.341648   
4     -2.028934  -2.977077 -19.282000  3.621475  ...  0.215418  0.484430   
...         ...        ...        ...       ...  ...       ...       ...   
2995 -18.477665 -22.479776   0.922552 -7.602468  ... -2.470063  4.421223   
2996 -15.861244 -10.180239  -4.867939 -0.662536  ... -2.227642  0.605481   
2997 -13.977830 -16.337875  -0.353709 -4.651527  ... -0.028793  3.763042   
2998 -14.844326 -19.795837  -4.025840 -4.273027  ... -3.241732 -0.987353   
2999 -15.025388 -19.491266  -0.536067 -6.233265  ... -2.224442  2.073195   

            31        32        33        34        35        36        37  \
0    -2.383272 -1.047149 -5.113010 -3.650117 -3.092591 -1.955777 -4.405060   
1    -1.837900 -0.798910 -4.694558 -4.464447 -1.893085 -2.912510 -4.858458   
2    -2.202147 -0.537667 -3.844402 -2.821896 -2.086511 -2.610275 -4.089844   
3    -1.725350 -0.643298 -3.470233 -2.856177 -2.057140 -1.870503 -4.755356   
4    -3.425826  0.476763 -4.416140 -2.720565 -2.072952 -1.341345 -5.566973   
...        ...       ...       ...       ...       ...       ...       ...   
2995  0.742409 -3.576027 -1.591279 -3.515108 -3.029455 -3.592587 -2.900054   
2996  1.392444 -0.948494 -3.438912  0.659637 -0.903038 -1.892453 -2.112316   
2997  1.154832 -4.393998 -5.090885 -2.760841 -1.561349 -3.028061 -4.226657   
2998  0.961699 -3.170674 -4.107362 -6.001142 -4.654924 -3.437292 -3.550606   
2999  3.516302 -1.918456 -0.355499 -1.424978 -2.336957 -1.454762 -6.149889   

            38  
0    -4.580990  
1    -4.174491  
2    -5.701215  
3    -4.600479  
4    -4.696309  
...        ...  
2995  0.754864  
2996 -1.224023  
2997  3.758476  
2998 -0.757205  
2999  0.243947  

[3000 rows x 39 columns]

In [12]:
scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x)
x_scaled

array([[0.67013833, 0.58616815, 0.78980671, ..., 0.41959673, 0.34055637,
        0.20356638],
       [0.62262296, 0.61282823, 0.74960329, ..., 0.35551453, 0.31245323,
        0.22893401],
       [0.67731041, 0.54007962, 0.69491761, ..., 0.3757583 , 0.36009458,
        0.13365865],
       ...,
       [0.75231092, 0.71111109, 0.37721184, ..., 0.34777489, 0.3516144 ,
        0.72399156],
       [0.70364204, 0.82622961, 0.38640471, ..., 0.32036449, 0.39351839,
        0.44219008],
       [0.70002728, 0.51735625, 0.45997196, ..., 0.45315483, 0.23240593,
        0.50466706]])

In [13]:
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
y_encoded

array([0, 0, 0, ..., 1, 1, 1])

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y_encoded, test_size=0.2, random_state=42)


In [17]:

input_shape = (x_train.shape[1],)


In [19]:
from sklearn.utils import class_weight
class_weights = dict(enumerate(class_weight.compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)))


In [20]:
inputs = Input(shape=input_shape)
x = Attention()([inputs, inputs])  # Use Attention layer instead of Dense
x = Dropout(0.5)(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.5)(x)
x = Dense(64, activation='tanh')(x)
x = Dropout(0.5)(x)
x = Dense(32, activation='sigmoid')(x)
x = Dropout(0.5)(x)
outputs = Dense(1, activation='sigmoid')(x)

In [29]:
model = Model(inputs=inputs, outputs=outputs)
model.compile(optimizer=Adam(learning_rate=0.01), loss='binary_crossentropy', metrics=['accuracy'])



In [30]:
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(patience=10, restore_best_weights=True)

In [31]:
model.fit(x_train, y_train, validation_data=(x_test, y_test), batch_size=32, epochs=20, callbacks=[early_stopping])

# Evaluate the model
_, train_accuracy = model.evaluate(x_train, y_train)
_, test_accuracy = model.evaluate(x_test, y_test)

print('Training Accuracy:', train_accuracy)
print('Testing Accuracy:', test_accuracy)


Epoch 1/20
75/75 [==============================] - 1s 6ms/step - loss: 0.6925 - accuracy: 0.5171 - val_loss: 0.6891 - val_accuracy: 0.5217
Epoch 2/20
75/75 [==============================] - 0s 3ms/step - loss: 0.6936 - accuracy: 0.5058 - val_loss: 0.6895 - val_accuracy: 0.5217
Epoch 3/20
75/75 [==============================] - 0s 4ms/step - loss: 0.6936 - accuracy: 0.5163 - val_loss: 0.6898 - val_accuracy: 0.5217
Epoch 4/20
75/75 [==============================] - 0s 3ms/step - loss: 0.6940 - accuracy: 0.5083 - val_loss: 0.6901 - val_accuracy: 0.5233
Epoch 5/20
75/75 [==============================] - 0s 3ms/step - loss: 0.6925 - accuracy: 0.5204 - val_loss: 0.6903 - val_accuracy: 0.6517
Epoch 6/20
75/75 [==============================] - 0s 4ms/step - loss: 0.6934 - accuracy: 0.5029 - val_loss: 0.6903 - val_accuracy: 0.6633
Epoch 7/20
75/75 [==============================] - 0s 4ms/step - loss: 0.6945 - accuracy: 0.5129 - val_loss: 0.6905 - val_accuracy: 0.8150
Epoch 8/20
75/75 [==

In [39]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow.keras.layers import Dense, Input, Dropout, Attention
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.metrics import classification_report

data = pd.read_excel("/content/Main Data Set.xlsx")
x = data.iloc[:, :-2]
y = data.iloc[:, -1]

scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x)

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

x_train, x_test, y_train, y_test = train_test_split(x_scaled, y_encoded, test_size=0.2, random_state=42)

input_shape = (x_train.shape[1],)

class_weights = dict(enumerate(class_weight.compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)))

inputs = Input(shape=input_shape)
x = Dense(256, activation='relu')(inputs)
x = Dropout(0.5)(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.5)(x)
x = Dense(64, activation='relu')(x)
x = Dropout(0.5)(x)

# Add Attention mechanism
attn_output = Attention()([x, x])

x = Dense(32, activation='relu')(attn_output)
x = Dropout(0.5)(x)
outputs = Dense(1, activation='sigmoid')(x)

model = Model(inputs=inputs, outputs=outputs)
model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])

early_stopping = EarlyStopping(patience=10, restore_best_weights=True)

model.fit(x_train, y_train, validation_data=(x_test, y_test), batch_size=32, epochs=20, callbacks=[early_stopping])

# Evaluate the model
_, train_accuracy = model.evaluate(x_train, y_train)
_, test_accuracy = model.evaluate(x_test, y_test)

print('Training Accuracy:', train_accuracy)
print('Testing Accuracy:', test_accuracy)


Epoch 1/20
75/75 [==============================] - 2s 6ms/step - loss: 0.6721 - accuracy: 0.5704 - val_loss: 0.5704 - val_accuracy: 0.9200
Epoch 2/20
75/75 [==============================] - 0s 4ms/step - loss: 0.4287 - accuracy: 0.8279 - val_loss: 0.1690 - val_accuracy: 0.9783
Epoch 3/20
75/75 [==============================] - 0s 4ms/step - loss: 0.2185 - accuracy: 0.9346 - val_loss: 0.0793 - val_accuracy: 0.9833
Epoch 4/20
75/75 [==============================] - 0s 5ms/step - loss: 0.1419 - accuracy: 0.9650 - val_loss: 0.0784 - val_accuracy: 0.9767
Epoch 5/20
75/75 [==============================] - 0s 4ms/step - loss: 0.1535 - accuracy: 0.9613 - val_loss: 0.0621 - val_accuracy: 0.9867
Epoch 6/20
75/75 [==============================] - 0s 4ms/step - loss: 0.1088 - accuracy: 0.9750 - val_loss: 0.0466 - val_accuracy: 0.9900
Epoch 7/20
75/75 [==============================] - 0s 4ms/step - loss: 0.1506 - accuracy: 0.9592 - val_loss: 0.1255 - val_accuracy: 0.9667
Epoch 8/20
75/75 [==

In [40]:
#4
input_sample=[0.577925,0.709901,0.688234,0.511104,0.910279,0.651897,0.752281,0.647049,0.370606,0.736650,0.669853,0.556179,0.420008,0.752727,0.759170,0.593053,0.562426,0.736432,0.504392,0.622027,0.364966,0.531934,0.221066,0.302269,0.287320,0.205320,0.268884,0.262020,0.213975,0.377164,0.449549,0.263653,0.465903,0.313177,0.375177,0.420458,0.460751,0.268537,0.196370]
len(input_sample)
input_sample = np.array(input_sample).reshape(1,39)
predictions = model.predict(input_sample)
predictions

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 161ms/step
[[0]]


In [41]:
#2599
input_sample=[0.712120,0.650542,0.366992,0.436288,0.428585,0.373965,0.687088,0.642749,0.686330,0.626207,0.468095,0.339787,0.584682,0.369466,0.463744,0.711811,0.482888,0.664246,0.481662,0.631933,0.521777,0.736818,0.678289,0.635984,0.828648,0.420239,0.479775,0.294975,0.133693,0.142501,0.396931,0.392093,0.430237,0.329627,0.330772,0.370938,0.354412,0.434149,0.383211]
input_sample = np.array(input_sample).reshape(1, 39)
predictions = model.predict(input_sample)
predictions
threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 23ms/step
[[1]]


In [42]:
#1499
input_sample=[0.697741, 0.525116, 0.545003, 0.692816, 0.457930, 0.359801, 0.461989, 0.315771, 0.490485, 0.428895, 0.669433, 0.294186, 0.603710, 0.517595, 0.442430, 0.583103, 0.683023, 0.505508, 0.506476, 0.355762, 0.302428, 0.292831, 0.054839, 0.251980, 0.439162, 0.346069, 0.717094, 0.573125, 0.496748, 0.452190, 0.556708, 0.442439, 0.613101, 0.533443, 0.404268, 0.594605, 0.536038, 0.537847, 0.326311]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 39)
predictions = model.predict(input_sample)
predictions
threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 43ms/step
[[0]]


In [43]:
#1500
input_sample=[0.872731, 0.411082, 0.480586, 1.000000, 0.253384, 0.528318, 0.296872, 0.394610, 0.502378,0.392042, 0.621543, 0.006626, 0.516975, 0.521456, 0.669484, 0.201321, 0.501754, 0.354544,0.311420, 0.320913, 0.236528, 0.187705, 0.124682, 0.319398, 0.362812, 0.542776, 0.778250,0.758794, 0.785707, 0.417236, 0.271772, 0.303650, 0.376029, 0.512281, 0.550409, 0.218163,0.291156, 0.418453, 0.608678]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 39)
predictions = model.predict(input_sample)
predictions
threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 22ms/step
[[1]]


In [45]:
x_scaled[200]

array([0.28751908, 0.17453525, 0.60371436, 0.37285213, 0.52680061,
       0.57972383, 0.66328006, 0.71982587, 0.48469603, 0.70401053,
       0.59750665, 0.38382807, 0.73242022, 0.62510992, 0.59665948,
       0.72737553, 0.5430308 , 0.83759825, 0.46905297, 0.5797158 ,
       0.41333878, 0.45646783, 0.24456293, 0.38179546, 0.25463077,
       0.30057015, 0.3363953 , 0.16092597, 0.37714372, 0.20258293,
       0.36938982, 0.3130389 , 0.41092834, 0.41059125, 0.56007651,
       0.56528194, 0.54568721, 0.69933096, 0.43438687])

In [46]:
#200
input_sample=[0.28751908, 0.17453525, 0.60371436, 0.37285213, 0.52680061,
       0.57972383, 0.66328006, 0.71982587, 0.48469603, 0.70401053,
       0.59750665, 0.38382807, 0.73242022, 0.62510992, 0.59665948,
       0.72737553, 0.5430308 , 0.83759825, 0.46905297, 0.5797158 ,
       0.41333878, 0.45646783, 0.24456293, 0.38179546, 0.25463077,
       0.30057015, 0.3363953 , 0.16092597, 0.37714372, 0.20258293,
       0.36938982, 0.3130389 , 0.41092834, 0.41059125, 0.56007651,
       0.56528194, 0.54568721, 0.69933096, 0.43438687]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 39)
predictions = model.predict(input_sample)
predictions
threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 22ms/step
[[0]]


In [47]:
x_scaled[1498]

array([0.75920735, 0.53596784, 0.4454522 , 0.6518067 , 0.37857654,
       0.49189194, 0.31242684, 0.45336126, 0.54342236, 0.49283143,
       0.68227883, 0.19398153, 0.73523579, 0.39517534, 0.44725313,
       0.61247257, 0.58290072, 0.60929531, 0.3737752 , 0.45377552,
       0.31542094, 0.35803424, 0.13088827, 0.31557783, 0.31464921,
       0.2887734 , 0.64523687, 0.27850363, 0.3735909 , 0.38714257,
       0.70224415, 0.4800565 , 0.70950169, 0.56203339, 0.58969428,
       0.63853391, 0.47482726, 0.66677148, 0.42561338])

In [48]:
#1498
input_sample=[0.75920735, 0.53596784, 0.4454522 , 0.6518067 , 0.37857654,
       0.49189194, 0.31242684, 0.45336126, 0.54342236, 0.49283143,
       0.68227883, 0.19398153, 0.73523579, 0.39517534, 0.44725313,
       0.61247257, 0.58290072, 0.60929531, 0.3737752 , 0.45377552,
       0.31542094, 0.35803424, 0.13088827, 0.31557783, 0.31464921,
       0.2887734 , 0.64523687, 0.27850363, 0.3735909 , 0.38714257,
       0.70224415, 0.4800565 , 0.70950169, 0.56203339, 0.58969428,
       0.63853391, 0.47482726, 0.66677148, 0.42561338]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 39)
predictions = model.predict(input_sample)
predictions
threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 23ms/step
[[0]]


In [50]:
model.save('Attention_System_Age_Estimation.h5')